# Use postgres/example user/password credentials

version: '3.1'
services:
  web:
    image: .
    depends_on:
      - db
    ports:
      - "8013:8013"
    volumes:
      - ./common/static/photo:/etc/bosch-estore/static/photo
    environment:
      - ENV=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass